### ISSUE TITLE
Could you please provide the link to download the datasets as I tried to run the code and I always get the following error:  Traceback (most recent call last):   File "e:\DroTrack-master\code\run.py", line 15, in <module>     boxes = bbox_helper.data2bboxes(data.data)   File "e:\DroTrack-master\code\utils\bbox_helper.py", line 42, in data2bboxes     with open(dataset['url']+class_dir+'/groundtruth_rect.txt') as f: FileNotFoundError: [Errno 2] No such file or directory: '../../DTB70/Animal1/groundtruth_rect.txt'

### ISSUE THREAD

**Issue by Abdullatif2** [cruiseresearchgroup/DroTrack#1]

**Comment by mark-91** [comment]
> _No description provided._

hi @Abdullatif2 
did you run code ?
can you please share how you run the code

**Comment by Abdullatif2** [comment]
Unfortunately, I couldn't so I used another one

**Comment by ali7amdi** [comment]
Please download the DTB70 dataset from the author page mentioned here: [https://github.com/flyers/drone-tracking](https://github.com/flyers/drone-tracking).

**Comment by mark-91** [comment]
> Unfortunately, I couldn't so I used another one

Please can you provide me the algorithm that you used if it is open source.

**Comment by mark-91** [comment]
> Please download the DTB70 dataset from the author page mentioned here: https://github.com/flyers/drone-tracking.

thank you for your reply
I am working on my college graduation project, which is programming a drone to tracking  a target
Please can you add a file to explain how I run your algorithm (documentation and requirements file as an example)
Thanks

**Comment by mark-91** [comment]
> Please download the DTB70 dataset from the author page mentioned here: https://github.com/flyers/drone-tracking.

I'm trying to  DTB70 dataset from the author page 
 but I can't download from the site. It needs a Chinese number and I don't have it. Is there another link please?

**Comment by ZeinabJalali4** [comment]
> Please download the DTB70 dataset from the author page mentioned here: https://github.com/flyers/drone-tracking.

Hi @ali7amdi,
would you please explain how to use this databse? Shal I run any code from the github repo you metioned?
